<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Intez</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">
    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="./css/style.css">
    <!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
    <script src="https://cbcmpgs.gateway.mastercard.com/form/version/65/merchant/TESTMALKEYRENUSD/session.js"></script>
    <!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
    <style id="antiClickjack">
        body {
            /* display: none !important; */
        }
    </style>
</head>

<body class="@@class">

    <div id="preloader">
        <i>.</i>
        <i>.</i>
        <i>.</i>
    </div>

    <div id="main-wrapper">

        <div class="authincation section-padding">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-xl-5 col-md-6">
                        <?php if($alert) { ?>
                        <div class="alert alert-success  fade show d-flex justify-content-between" role="alert">
                            <span>Please enter verification token from your device</span>
                            <span class="c-pointer" data-dismiss="alert">
                                <i class="icofont-close-line"></i>
                            </span>
                        </div>
                        <?php } ?>
                        <div class="mini-logo text-center my-3">
                            <a href="./index.html"><img src="./images/logo.png" alt=""></a>
                            <h4 class="card-title mt-5">2-Step Verification</h4>
                        </div>
                        <div class="auth-form card">
                            <div class="card-body">
                                <p class="text-center mb-3">Enter the verification code generated by your phone ending
                                    in +xxx xxxxxxxx60.</p>
                                <form action="otp-2.html" class="row g-3">
                                    <div class="col-12">
                                        <label class="form-label">Card Number</label>
                                        <input type="text" id="card-number" class="form-control" title="card number" aria-label="enter your card number" value="" tabindex="1" readonly>
                                    </div>
                                    <div class="col-2">
                                        <label class="form-label">MM</label>
                                        <input type="text" id="expiry-month" class="form-control" title="expiry month" aria-label="two digit expiry month" value="" tabindex="2" readonly>
                                    </div>
                                    <div class="col-2">
                                        <label class="form-label">YY</label>
                                        <input type="text" id="expiry-year" class="form-control" title="expiry year" aria-label="two digit expiry year" value="" tabindex="3" readonly>
                                    </div>
                                    <div class="col-2">
                                        <label class="form-label">MdM</label>
                                        <input type="text" id="expiry-month" class="form-control" title="expiry month" aria-label="two digit expiry month" value="" tabindex="2" readonly>
                                    </div>
                                    <div class="col-3">
                                        <label class="form-label">CVC</label>
                                        <input type="text" id="security-code" class="form-control" title="security code" aria-label="three digit CCV security code" value="" tabindex="4" readonly>
                                    </div>
                                    <div class="col-3">
                                        &nbsp;
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label">Cardholder Name</label>
                                        <input type="text" id="cardholder-name" class="form-control" title="cardholder name" aria-label="enter name on card" value="" tabindex="5" readonly>
                                    </div>
                                    <div class="alert-text">
                                        <small>Security is critical in Xtrader. to help keep your account safe, we'll
                                            text
                                            you
                                            a verification code when you sign in on a new device</small>
                                    </div>
                                    <div class="text-center mt-4">
                                        <button id="payButton" onclick="pay('card');" type="submit" class="btn btn-primary btn-block">Pay Now</button>
                                    </div>
                                </form>
                                <div class="new-account mt-3">
                                    <p>Don't get code? <a class="text-primary" href="otp-1.html">Resend</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- JAVASCRIPT FRAME-BREAKER CODE TO PROVIDE PROTECTION AGAINST IFRAME CLICK-JACKING -->
    <script type="text/javascript">
        if (self === top) {
            var antiClickjack = document.getElementById("antiClickjack");
            antiClickjack.parentNode.removeChild(antiClickjack);
        } else {
            top.location = self.location;
        }

        PaymentSession.configure({
            session: "<your_session_ID>",
            fields: {
                // ATTACH HOSTED FIELDS TO YOUR PAYMENT PAGE FOR A CREDIT CARD
                card: {
                    number: "#card-number",
                    securityCode: "#security-code",
                    expiryMonth: "#expiry-month",
                    expiryYear: "#expiry-year",
                    nameOnCard: "#cardholder-name"
                }
            },
            //SPECIFY YOUR MITIGATION OPTION HERE
            frameEmbeddingMitigation: ["javascript"],
            callbacks: {
                initialized: function(response) {
                    // HANDLE INITIALIZATION RESPONSE
                },
                formSessionUpdate: function(response) {
                    // HANDLE RESPONSE FOR UPDATE SESSION
                    if (response.status) {
                        if ("ok" == response.status) {
                            console.log("Session updated with data: " + response.session.id);

                            //check if the security code was provided by the user
                            if (response.sourceOfFunds.provided.card.securityCode) {
                                console.log("Security code was provided.");
                            }

                            //check if the user entered a Mastercard credit card
                            if (response.sourceOfFunds.provided.card.scheme == 'MASTERCARD') {
                                console.log("The user entered a Mastercard credit card.")
                            }
                        } else if ("fields_in_error" == response.status) {

                            console.log("Session update failed with field errors.");
                            if (response.errors.cardNumber) {
                                console.log("Card number invalid or missing.");
                            }
                            if (response.errors.expiryYear) {
                                console.log("Expiry year invalid or missing.");
                            }
                            if (response.errors.expiryMonth) {
                                console.log("Expiry month invalid or missing.");
                            }
                            if (response.errors.securityCode) {
                                console.log("Security code invalid.");
                            }
                        } else if ("request_timeout" == response.status) {
                            console.log("Session update failed with request timeout: " + response.errors.message);
                        } else if ("system_error" == response.status) {
                            console.log("Session update failed with system error: " + response.errors.message);
                        }
                    } else {
                        console.log("Session update failed: " + response);
                    }
                }
            },
            interaction: {
                displayControl: {
                    formatCard: "EMBOSSED",
                    invalidFieldCharacters: "REJECT"
                }
            }
        });

        function pay() {
            // UPDATE THE SESSION WITH THE INPUT FROM HOSTED FIELDS
            PaymentSession.updateSessionFromForm('card');
        }

        $('#card-number').validateCreditCard(function(result) {
            if (result.valid) {
                $(this).addClass('cc-valid');
            } else {
                $(this).removeClass('cc-valid');
            }
        });
    </script>
    <!-- <script src="./vendor/jquery/jquery.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha512-bnIvzh6FU75ZKxp0GXLH9bewza/OIw6dLVh9ICg0gogclmYGguQJWl8U30WpbsGTqbIiAwxTsbe76DErLq5EDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- <script src="./vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0-alpha3/js/bootstrap.bundle.min.js" integrity="sha512-4mKgMjjiLqHCkqTX9YRfreevkJHBzF1d5GT7HKaFr/dLQqTKNvFl3m6fwTedsbc039MVQPAFIA1s8hP64H3LFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-creditcardvalidator/1.0.0/jquery.creditCardValidator.min.js" integrity="sha512-7omJBgl5QF4QuC3Ge745IO3rDZVMrZWIGK8lSs5lQIFxbWt4d2c7YQg3ZcnonFyRuQslrJ1Ai33Zj/rnXC15+Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="./js/scripts.js"></script>

</body>

</html>